>Use crammer's rule to solve

$$
\begin{cases}
0.3x+0.52y+z = -0.01 \\
0.5x +y + 1.9z = 0.67\\
0.1x + 0.3y + 0.5z = -0.44
\end{cases}
$$

In [5]:
!pip install numpy

In [22]:
import numpy as np
A = np.array([[0.3, 0.52, 1],[0.5, 1, 1.9],[0.1, 0.3, 0.5]])
b = np.array([[-0.01],[0.67],[-0.44]])

D = A[0,0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) - A[0,1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) + A[0,2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])

A_b1 = np.array([[-0.01, 0.52, 1],[0.67, 1, 1.9],[-0.44, 0.3, 0.5]])
D_1 = A_b1[0,0] * (A_b1[1, 1] * A_b1[2, 2] - A_b1[1, 2] * A_b1[2, 1]) - A_b1[0,1] * (A_b1[1, 0] * A_b1[2, 2] - A_b1[1, 2] * A_b1[2, 0]) + A_b1[0,2] * (A_b1[1, 0] * A_b1[2, 1] - A_b1[1, 1] * A_b1[2, 0])
x_1 = D_1 / D
print (x_1)

A_b2 = np.array([[0.3, -0.01, 1],[0.5, 0.67, 1.9],[0.1, -0.44, 0.5]])
D_2 = A_b2[0,0] * (A_b2[1, 1] * A_b2[2, 2] - A_b2[1, 2] * A_b2[2, 1]) - A_b2[0,1] * (A_b2[1, 0] * A_b2[2, 2] - A_b2[1, 2] * A_b2[2, 0]) + A_b2[0,2] * (A_b2[1, 0] * A_b2[2, 1] - A_b2[1, 1] * A_b2[2, 0])
x_2 = D_2 / D

print(x_2)
A_b3 = np.array([[0.3, 0.52, -0.01],[0.5, 1, 0.67],[0.1, 0.3, -0.44]])
D_3 = A_b3[0,0] * (A_b3[1, 1] * A_b3[2, 2] - A_b3[1, 2] * A_b3[2, 1]) - A_b3[0,1] * (A_b3[1, 0] * A_b3[2, 2] - A_b3[1, 2] * A_b3[2, 0]) + A_b3[0,2] * (A_b3[1, 0] * A_b3[2, 1] - A_b3[1, 1] * A_b3[2, 0])
x_3 = D_3 / D

print(x_3)

-14.900000000000057
-29.500000000000068
19.80000000000005


In [25]:
A_inv = np.linalg.inv(A)
print(A_inv @ b)
print(np.linalg.det(A_b1) / np.linalg.det(A))

[[-14.9]
 [-29.5]
 [ 19.8]]
-14.899999999999933


>[!Example]
Use Gauss elimination to solve

$$
\begin{cases}
3x-0.1y-0.2z = -7.85 \\
0.1x +7y - 0.3z = -19.3\\
0.3x - 0.2y + 10z = 71.4
\end{cases}
$$



In [85]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]])
b = np.array([[7.85],[-19.3],[71.4]])
# Eliminar Columna 1 (Operaciones Fila (2) y (3))
m_1 = A[1,0] / A[0, 0]
m_2 = A[2,0] / A[0, 0]
A[1, :] = A[1, :] - A[0, :] * m_1
b[1] = b[1] - b[0] * m_1
A[2, :] = A[2, :] - A[0, :] * m_2
b[2] = b[2] - b[0] * m_2
# Eliminar Columna 2
m_1 = A[2,1] / A[1, 1]
A[2, :] = A[2, :] - A[1, :] * m_1
b[2] = b[2] - b[1] * m_1
print(A)
x_3 = (b[2]) / A[2, 2]
x_2 = (b[1] - A[1, 2] * x_3) / A[1,1]
x_1 = (b[0] - A[0, 1] * x_2 - A[0, 2] * x_3) / A[0, 0]
print(x_3, x_2, x_1)

[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]
[7.] [-2.5] [3.]


In [30]:
A_inv = np.linalg.inv(A)
print(A_inv @ b)
print(np.linalg.det(A_b1) / np.linalg.det(A))

[[ 3. ]
 [-2.5]
 [ 7. ]]
0.000155833289755791


In [74]:
print(A, b)

[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]] [[  7.85      ]
 [-19.56166667]
 [ 70.08429319]]
