In [7]:
import numpy as np


>Use crammer's rule to solve

$$
\begin{cases}
0.3x+0.52y+z = -0.01 \\
0.5x +y + 1.9z = 0.67\\
0.1x + 0.3y + 0.5z = -0.44
\end{cases}
$$

In [2]:
A = np.array([[0.3, 0.52, 1],[0.5, 1, 1.9],[0.1, 0.3, 0.5]])
b = np.array([[-0.01],[0.67],[-0.44]])

D = A[0,0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) - A[0,1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) + A[0,2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])

A_b1 = np.array([[-0.01, 0.52, 1],[0.67, 1, 1.9],[-0.44, 0.3, 0.5]])
D_1 = A_b1[0,0] * (A_b1[1, 1] * A_b1[2, 2] - A_b1[1, 2] * A_b1[2, 1]) - A_b1[0,1] * (A_b1[1, 0] * A_b1[2, 2] - A_b1[1, 2] * A_b1[2, 0]) + A_b1[0,2] * (A_b1[1, 0] * A_b1[2, 1] - A_b1[1, 1] * A_b1[2, 0])
x_1 = D_1 / D
print (x_1)

A_b2 = np.array([[0.3, -0.01, 1],[0.5, 0.67, 1.9],[0.1, -0.44, 0.5]])
D_2 = A_b2[0,0] * (A_b2[1, 1] * A_b2[2, 2] - A_b2[1, 2] * A_b2[2, 1]) - A_b2[0,1] * (A_b2[1, 0] * A_b2[2, 2] - A_b2[1, 2] * A_b2[2, 0]) + A_b2[0,2] * (A_b2[1, 0] * A_b2[2, 1] - A_b2[1, 1] * A_b2[2, 0])
x_2 = D_2 / D

print(x_2)
A_b3 = np.array([[0.3, 0.52, -0.01],[0.5, 1, 0.67],[0.1, 0.3, -0.44]])
D_3 = A_b3[0,0] * (A_b3[1, 1] * A_b3[2, 2] - A_b3[1, 2] * A_b3[2, 1]) - A_b3[0,1] * (A_b3[1, 0] * A_b3[2, 2] - A_b3[1, 2] * A_b3[2, 0]) + A_b3[0,2] * (A_b3[1, 0] * A_b3[2, 1] - A_b3[1, 1] * A_b3[2, 0])
x_3 = D_3 / D

print(x_3)

-14.900000000000057
-29.500000000000068
19.80000000000005


In [3]:
A_inv = np.linalg.inv(A)
print(A_inv @ b)
print(np.linalg.det(A_b1) / np.linalg.det(A))

[[-14.9]
 [-29.5]
 [ 19.8]]
-14.899999999999933


>[!Example]
Use Gauss elimination to solve

$$
\begin{cases}
3x-0.1y-0.2z = -7.85 \\
0.1x +7y - 0.3z = -19.3\\
0.3x - 0.2y + 10z = 71.4
\end{cases}
$$



In [4]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]])
b = np.array([[7.85],[-19.3],[71.4]])
# Eliminar Columna 1 (Operaciones Fila (2) y (3))
m_1 = A[1,0] / A[0, 0]
m_2 = A[2,0] / A[0, 0]
A[1, :] = A[1, :] - A[0, :] * m_1
b[1] = b[1] - b[0] * m_1
A[2, :] = A[2, :] - A[0, :] * m_2
b[2] = b[2] - b[0] * m_2
# Eliminar Columna 2
m_1 = A[2,1] / A[1, 1]
A[2, :] = A[2, :] - A[1, :] * m_1
b[2] = b[2] - b[1] * m_1
print(A)
x_3 = (b[2]) / A[2, 2]
x_2 = (b[1] - A[1, 2] * x_3) / A[1,1]
x_1 = (b[0] - A[0, 1] * x_2 - A[0, 2] * x_3) / A[0, 0]
print(x_3, x_2, x_1)

[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]
[7.] [-2.5] [3.]


In [5]:
A_inv = np.linalg.inv(A)
print(A_inv @ b)
print(np.linalg.det(A_b1) / np.linalg.det(A))

[[ 3. ]
 [-2.5]
 [ 7. ]]
0.000155833289755791


In [6]:
print(A, b)

[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]] [[  7.85      ]
 [-19.56166667]
 [ 70.08429319]]


In [280]:
def linear_system_solve(A, b):
    size = np.shape(A)
    if size[0] == size[1]:
        n = size[0]
        print(n)
        print(f'El tamaño de su matriz es {size}')
        vect_sol = np.zeros((n, 1))
        # Eliminación
        for i in range(n - 1):
            if A[i,i] == 0:
                raise ValueError("Pivote 0")
            for j in range(i + 1, n):
                factor = A[j, i] / A[i, i]
                A[j, :] = A[j, :] - A[i, :] * factor 
                b[j, 0] = b[j, 0] - b[i, 0] * factor 
        print(f"Sistema reducido: {A}, {b}")
        # solución x_n
        for i in range(n - 1, -1, -1):
            suma = 0
            for j in range(i + 1, n):
                suma += A[i, j] * vect_sol[j, 0]
            vect_sol[i, 0] = (b[i, 0] - suma) / A[i, i]
        print(f"El Vector Solución es: {vect_sol}")
        return vect_sol
    else:
        print(f'El tamaño de su matriz es {size}')
        return "Ingrese una matriz cuadrada nxn  (Ej: 3x3)"

In [281]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]])
b = np.array([[7.85],[-19.3],[71.4]])
linear_system_solve(A , b)

3
El tamaño de su matriz es (3, 3)
Sistema reducido: [[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]], [[  7.85      ]
 [-19.56166667]
 [ 70.08429319]]
El Vector Solución es: [[ 3. ]
 [-2.5]
 [ 7. ]]


array([[ 3. ],
       [-2.5],
       [ 7. ]])

In [282]:
vect_sol = np.zeros((3, 1))
vect_sol[1]
A_inv = np.linalg.inv(A)
print(A_inv @ b)

[[ 3. ]
 [-2.5]
 [ 7. ]]


In [347]:
def gauss_naive(A, b):
    A = A.copy()
    b = b.copy()
    size = np.shape(A)
    if size[0] == size[1]:
        n = size[0]
        vect_sol = np.zeros((n, 1))
        for i in range(n - 1):
            for j in range(i + 1, n):
                alpha = A[j][i] / A[i][i] # <-- pivote
                A[j][:] = A[j][:] - A[i][:] * alpha
                b[j][0] = b[j][0] - b[i][0] * alpha
        # Susitución hacía atras
        for i in range(n - 1, -1, -1):
            suma = 0
            for j in range(i + 1, n):
                suma += A[i][j] * vect_sol[j][0]
            vect_sol[i][0] = (b[i][0] - suma) / A[i][i]
        print(f'el sistema reducido esta dado por: {A},\n {b}')
        print(f'El Vector Solución esta dado por: {vect_sol}')
    else:
        return "Este código solo permite matrices nxn (Ej: 2x2, 3x3, 4x4, etc)"    

In [348]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]])
b = np.array([[7.85],[-19.3],[71.4]])

gauss_naive(A , b)


el sistema reducido esta dado por: [[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]],
 [[  7.85      ]
 [-19.56166667]
 [ 70.08429319]]
El Vector Solución esta dado por: [[ 3. ]
 [-2.5]
 [ 7. ]]


In [355]:
def gauss_naive(A, b):
    A = A.copy()
    b = b.copy()
    size = np.shape(A)
    if size[0] == size[1]:
        n = size[0]
        vect_sol = np.zeros((n, 1))
        for j in range(n - 1):
            for i in range(j, n - 1):
                if j == i:
                    c = A[i][j]
                alpha = A[i + 1][j] / c # <-- pivote
                A[i + 1][:] = A[i + 1][:] - A[j][:] * alpha
                b[i + 1][0] = b[i + 1][0] - b[j][0] * alpha
        # Susitución hacía atras
        for i in range(n - 1, -1, -1):
            suma = 0
            for j in range(i + 1, n):
                suma += A[i][j] * vect_sol[j][0]
            vect_sol[i][0] = (b[i][0] - suma) / A[i][i]
        print(f'El Vector Solución esta dado por: {vect_sol}')
    else:
        return "Este código solo permite matrices nxn (Ej: 2x2, 3x3, 4x4, etc)"    

In [356]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]])
b = np.array([[7.85],[-19.3],[71.4]])

gauss_naive(A , b)


El Vector Solución esta dado por: [[ 3. ]
 [-2.5]
 [ 7. ]]


In [408]:
def gauss(A, b):
    
    A = A.copy()
    b = b.copy()
    size = np.shape(A)
    if size[0] == size[1]:
        n = size[0]
        vect_sol = np.zeros((n, 1)) 
                
        # Eliminación
        for i in range(n - 1):
            # Verificación Pivote
            if A[i][i] == 0:
                for k in range(i + 1, n):
                    if A[k][i] != 0:
                        #intercambio filas
                        A[[i, k]] = A[[k, i]]
                        b[[i, k]] = b[[k, i]]
                        break
                        
            for j in range(i + 1, n):
                alpha = A[j][i] / A[i][i] # <-- pivote
                A[j][:] = A[j][:] - A[i][:] * alpha
                b[j][0] = b[j][0] - b[i][0] * alpha
        # Susitución hacía atras
        for i in range(n - 1, -1, -1):
            suma = 0
            for j in range(i + 1, n):
                suma += A[i][j] * vect_sol[j][0]
            vect_sol[i][0] = (b[i][0] - suma) / A[i][i]
        print(f'el sistema reducido esta dado por: {A},\n {b}')
        print(f'El Vector Solución esta dado por: {vect_sol}')
    else:
        return "Este código solo permite matrices nxn (Ej: 2x2, 3x3, 4x4, etc)"    

In [410]:
A = np.array([
    [0, 2, 1, 3],
    [1, -1, 2, 1],
    [2, 3, -1, 4],
    [1, 1, 1, 1]
], dtype=float)

b = np.array([
    [10],
    [3],
    [7],
    [4]
], dtype=float)
gauss(A, b)

el sistema reducido esta dado por: [[ 1.         -1.          2.          1.        ]
 [ 0.          2.          1.          3.        ]
 [ 0.          0.         -7.5        -5.5       ]
 [ 0.          0.          0.         -1.53333333]],
 [[  3. ]
 [ 10. ]
 [-24. ]
 [ -2.6]]
El Vector Solución esta dado por: [[-1.13043478]
 [ 1.47826087]
 [ 1.95652174]
 [ 1.69565217]]


In [407]:
print(A)
A[[0, 1]] = A[[1, 0]]
print(A, b)

[[ 0.  2.  1.  3.]
 [ 1. -1.  2.  1.]
 [ 2.  3. -1.  4.]
 [ 1.  1.  1.  1.]]
[[ 1. -1.  2.  1.]
 [ 0.  2.  1.  3.]
 [ 2.  3. -1.  4.]
 [ 1.  1.  1.  1.]] [[10.]
 [ 3.]
 [ 7.]
 [ 4.]]


>[!Example] Use the gauss-jordan technique to so]lve the same system

$$
\begin{cases}
3x-0.1y-0.2z = 7.85 \\
0.1x +7y - 0.3z = -19.3\\
0.3x - 0.2y + 10z = 71.4
\end{cases}
$$

In [4]:
import numpy as np

In [96]:
def gauss_jordan(A, b):
    A_sol = A.copy()
    b_sol = b.copy()
    size = np.shape(A)
    if size[0] == size[1]:
        n = size[0]
        
        if A_sol[0][0] != 0:
            # Eliminación inferior
            for i in range(n):
                b_sol[i][0] = b_sol[i][0] / A_sol[i][i] # tiene que ir primero, necesita utilizar el valor de A_sol sin modificar
                A_sol[i][:] = A_sol[i][:] / A_sol[i][i]

                for j in range(i + 1, n):
                    theta = A_sol[j][i] / A_sol[i][i]
                    A_sol[j][:] = A_sol[j][:] - A_sol[i][:] * theta
                    b_sol[j][0] = b_sol[j][0] - b_sol[i][0] * theta                

        print(A_sol, b_sol)
    else:
        return "Este código solo funciona para matrices cuadradas Ejemplo: 2x2, 3x3"            

In [97]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]], dtype = float)
b = np.array([[7.85],[-19.3],[71.4]], dtype = float)
gauss_jordan(A, b)

[[ 1.         -0.03333333 -0.06666667]
 [ 0.          1.         -0.04188482]
 [ 0.          0.          1.        ]] [[ 2.61666667]
 [-2.79319372]
 [ 7.        ]]


In [71]:
np.linalg.solve(A, b)

array([[ 3. ],
       [-2.5],
       [ 7. ]])

In [ ]:
A = np.array([[3, -0.1, -0.2],[0.1, 7, -0.3],[0.3, -0.2, 10]], dtype = float)
b = np.array([[7.85],[-19.3],[71.4]], dtype = float)
gauss_jordan(A, b)

In [127]:
def gauss_seidel(A, b):
    A_ = A.copy()
    b_ = b.copy()
    size = np.shape(A)
    n = size[0]
    vect_sol = np.zeros(n)
    for i in range(10):
        print(f"iteración {i + 1}")
        x0_old = vect_sol[0]
        x1_old = vect_sol[2]
        x2_old = vect_sol[1]
        vect_sol[0] = (b_[0][0] - A_[0][1] * vect_sol[1] - A_[0][2] * vect_sol[2]) / A_[0][0]
        vect_sol[1] = (b_[1][0] - A_[1][0] * vect_sol[0] - A_[1][2] * vect_sol[2]) / A_[1][1]
        vect_sol[2] = (b_[2][0] - A_[2][0] * vect_sol[0] - A_[2][1] * vect_sol[1]) / A_[2][2]
        print(f"Error relativo absoluto {np.abs((vect_sol[0] -x0_old) / vect_sol[0] * 100)}")
        if (vect_sol[0] -x0_old) / vect_sol[0] * 100 <= 0.1:
            break
        for k in range(n):
            print(f'{vect_sol[k]}')

In [128]:
gauss_seidel(A, b)
np.linalg.solve(A, b)

iteración 1
Error relativo absoluto 100.0
2.6166666666666667
-2.7945238095238096
7.005609523809525
iteración 2
Error relativo absoluto 12.502349989963122
2.990556507936508
-2.499624684807256
7.00029081106576
iteración 3
Error relativo absoluto 0.31584297423301044
3.0000318979108087
-2.499987992353051
6.999999283215615
iteración 4
Error relativo absoluto 0.0010515145943187922


array([[ 3. ],
       [-2.5],
       [ 7. ]])

In [130]:
A = np.array([[1, 1/2, 1/3],
              [1, 2/3, 1/2],
              [1, 3/4, 3/5]], dtype = float)
b = np.array([1.8333,2.16667,2.35])
np.linalg.solve(A, b)


array([0.99964, 1.00152, 0.9987 ])

In [131]:
np.linalg.det(A)

np.float64(0.0027777777777777675)